import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        void: "var(--color-void)",
        carbon: "var(--color-carbon)",
        obsidian: "var(--color-obsidian)",
        graphite: "var(--color-graphite)",
        smoke: "var(--color-smoke)",
        ash: "var(--color-ash)",
        fog: "var(--color-fog)",
        mist: "var(--color-mist)",
        bone: "var(--color-bone)",
        paper: "var(--color-paper)",
        "acid-lime": "var(--color-acid-lime)",
        "pulse-green": "var(--color-pulse-green)",
        "coral-red": "var(--color-coral-red)",
        "signal-teal": "var(--color-signal-teal)",
        "iris-violet": "var(--color-iris-violet)",
        lavender: "var(--color-lavender)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        muted: "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",
        primary: "var(--primary)",
        "primary-foreground": "var(--primary-foreground)",
        secondary: "var(--secondary)",
        "secondary-foreground": "var(--secondary-foreground)",
        destructive: "var(--destructive)",
        card: "var(--card)",
        "card-foreground": "var(--card-foreground)",
        accent: "var(--accent)",
        "accent-foreground": "var(--accent-foreground)",
      },
      fontFamily: {
        sans: [
          "var(--font-inter-variable)",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
        ],
        mono: [
          "var(--font-berkeley-mono)",
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "monospace",
        ],
      },
      fontWeight: {
        light: "300",
        normal: "400",
        medium: "510",
        semibold: "590",
      },
      fontSize: {
        caption: ["13px", { lineHeight: "1.2", fontWeight: "400" }],
        "body-sm": [
          "15px",
          { lineHeight: "1.6", letterSpacing: "-0.165px", fontWeight: "400" },
        ],
        "body-lg": [
          "20px",
          { lineHeight: "1.33", letterSpacing: "-0.24px", fontWeight: "590" },
        ],
        subheading: [
          "24px",
          { lineHeight: "1.33", letterSpacing: "-0.288px", fontWeight: "400" },
        ],
        "heading-sm": [
          "32px",
          { lineHeight: "1.13", letterSpacing: "-0.704px", fontWeight: "400" },
        ],
        heading: [
          "48px",
          { lineHeight: "1", letterSpacing: "-1.056px", fontWeight: "510" },
        ],
        "heading-lg": [
          "64px",
          { lineHeight: "1", letterSpacing: "-1.408px", fontWeight: "510" },
        ],
        display: [
          "72px",
          { lineHeight: "1", letterSpacing: "-1.584px", fontWeight: "510" },
        ],
      },
      spacing: {
        "ds-4": "4px",
        "ds-8": "8px",
        "ds-12": "12px",
        "ds-16": "16px",
        "ds-20": "20px",
        "ds-24": "24px",
        "ds-28": "28px",
        "ds-32": "32px",
        "ds-36": "36px",
        "ds-40": "40px",
        "ds-48": "48px",
        "ds-56": "56px",
        "ds-64": "64px",
        "ds-80": "80px",
        "ds-96": "96px",
        "ds-128": "128px",
      },
      maxWidth: {
        page: "1200px",
      },
      borderRadius: {
        sm: "2px",
        md: "6px",
        lg: "6px",
        xl: "12px",
        cards: "12px",
        badges: "4px",
        inputs: "6px",
        buttons: "6px",
        full: "9999px",
      },
      boxShadow: {
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        subtle: "var(--shadow-subtle)",
        "subtle-2": "var(--shadow-subtle-2)",
        "subtle-3": "var(--shadow-subtle-3)",
        xl: "var(--shadow-xl)",
        "subtle-4": "var(--shadow-subtle-4)",
        "subtle-5": "var(--shadow-subtle-5)",
        acid: "var(--shadow-acid)",
      },
      letterSpacing: {
        tightest: "-0.022em",
        tighter: "-0.012em",
        tight: "-0.011em",
      },
    },
  },
  plugins: [],
};
export default config;
